version: '3.8'

services:
  dbase:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doodle
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    networks:
      - doodle-network
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  webui:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./test.env
    depends_on:
      dbase:
        condition: service_healthy
    networks:
      - doodle-network

networks:
  doodle-network:
